### ISSUE TITLE
Question about scripts

### ISSUE THREAD

**Issue by john-delivuk** [leboncoin/terraform-aws-nvme-example#1]
Looking over them it looks like you've done this in a way that wont break if this is to run on a non-nitro instance class like a c4, or r4. Just wanted to confirm.

**Comment by aladjadj** [comment]
Hi @john-delivuk,
True, normally it's transparently if you don't have 'nvme' instances like C5* M5* ...,
also is useless to implement 'ebs_alias.sh.tpl' if not necessary, but you can implement part of this example to auto-mount ebs for example.
